# -*- coding: utf-8 -*-
"""nba_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_fw5dysO6awqa8OT2YBW24XrvsdXjUp
"""

!pip install -q pymupdf chromadb sentence-transformers langchain-text-splitters google-generativeai

from google.colab import drive
drive.mount('/content/drive')

import os

PROJECT_DIR = "/content/drive/MyDrive/Colab Notebooks/NLP/NBA RAG chatbot"
PDF_FOLDER  = f"{PROJECT_DIR}/pdfs"
DOCS_FOLDER = f"{PROJECT_DIR}/docs"
DB_PATH     = f"{PROJECT_DIR}/nba_vectordb"

os.makedirs(DOCS_FOLDER, exist_ok=True)
print("✅ Paths set")

from google.colab import userdata
import google.generativeai as genai

GOOGLE_API_KEY = userdata.get('GEMINI_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-2.5-flash-lite')
print("✅ Gemini ready")

import chromadb
from chromadb.utils import embedding_functions

client = chromadb.PersistentClient(path=DB_PATH)
ef = embedding_functions.SentenceTransformerEmbeddingFunction("all-MiniLM-L6-v2")
collection = client.get_or_create_collection("nba_docs", embedding_function=ef)
print(f"✅ DB connected — {collection.count()} chunks stored so far")

import fitz
import time
from langchain_text_splitters import RecursiveCharacterTextSplitter

# ── Chunking ──────────────────────────────────────────────────────────────────
def chunk_documents(pages, chunk_size=500, chunk_overlap=75):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size, chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""]
    )
    chunks = []
    for page in pages:
        for i, text in enumerate(splitter.split_text(page["content"])):
            chunks.append({"text": text, "metadata": {
                "doc_id": page["id"], "title": page["title"],
                "source": page["source"], "page": page["page"], "chunk_idx": i
            }})
    return chunks

# ── Ingestion ─────────────────────────────────────────────────────────────────
def ingest_chunks(chunks):
    ids       = [f"{c['metadata']['doc_id']}_c{c['metadata']['chunk_idx']}" for c in chunks]
    documents = [c["text"] for c in chunks]
    metadatas = [c["metadata"] for c in chunks]
    for i in range(0, len(chunks), 100):
        collection.upsert(
            ids=ids[i:i+100],
            documents=documents[i:i+100],
            metadatas=metadatas[i:i+100]
        )
    print(f"  ✅ Stored {len(chunks)} chunks — DB total: {collection.count()}")

# ── PDF ingestion ─────────────────────────────────────────────────────────────
def ingest_pdf(path):
    print(f"\n📥 Ingesting: {os.path.basename(path)}")
    doc = fitz.open(path)
    pages = []
    for page_num in range(len(doc)):
        text = doc[page_num].get_text("text").strip()
        if len(text) < 80:
            continue
        pages.append({
            "id":      f"{os.path.basename(path)}_p{page_num+1}",
            "title":   os.path.basename(path).replace(".pdf", ""),
            "source":  os.path.basename(path),
            "page":    page_num + 1,
            "content": text
        })
    doc.close()
    print(f"  📄 Extracted {len(pages)} pages")
    chunks = chunk_documents(pages)
    ingest_chunks(chunks)

# ── TXT ingestion with name enrichment ───────────────────────────────────────
def ingest_txt(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    filename   = os.path.basename(filepath)
    first_line = content.split("\n")[0].replace("PLAYER PROFILE: ", "").replace("TEAM PROFILE: ", "").replace("GAME LOG: ", "").replace("NBA LEAGUE LEADERS — ", "").strip()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=2000, chunk_overlap=200,
        separators=["\n\n", "\n", ". ", " ", ""]
    )
    raw_chunks = splitter.split_text(content)

    chunks = []
    for i, text in enumerate(raw_chunks):
        # Prepend name to every chunk so retrieval always connects numbers to the right player/team
        enriched_text = f"{first_line}\n{text}"
        chunks.append({"text": enriched_text, "metadata": {
            "doc_id":    filename,
            "title":     first_line,
            "source":    filename,
            "page":      1,
            "chunk_idx": i
        }})

    ingest_chunks(chunks)

# ── Retrieval ─────────────────────────────────────────────────────────────────
def retrieve(query, top_k=8):
    results = collection.query(
        query_texts=[query], n_results=top_k,
        include=["documents", "metadatas", "distances"]
    )
    return [{
        "text":     results["documents"][0][i],
        "metadata": results["metadatas"][0][i],
        "score":    1 - results["distances"][0][i]
    } for i in range(len(results["documents"][0]))]

print("✅ All helper functions defined")

for f in os.listdir(PDF_FOLDER):
    if f.endswith(".pdf"):
        ingest_pdf(os.path.join(PDF_FOLDER, f))

print("\n🏀 PDF ingestion complete!")



"""Collecting NBA Stats"""

from nba_api.stats.endpoints import (
    playercareerstats, commonplayerinfo,
    teamyearbyyearstats, playergamelog, leagueleaders
)
from nba_api.stats.static import players, teams

def save_doc(filename, content):
    filepath = os.path.join(DOCS_FOLDER, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

def safe_call(fn, *args, **kwargs):
    for attempt in range(3):
        try:
            time.sleep(0.6)
            return fn(*args, **kwargs)
        except Exception as e:
            print(f"    ⚠️  Attempt {attempt+1} failed: {e}")
            time.sleep(2)
    return None

TOP_PLAYERS = [
    "LeBron James", "Stephen Curry", "Kevin Durant", "Giannis Antetokounmpo",
    "Nikola Jokic", "Luka Doncic", "Joel Embiid", "Jayson Tatum",
    "Damian Lillard", "Anthony Davis", "Jimmy Butler", "Devin Booker",
    "Trae Young", "Ja Morant", "Zion Williamson", "Anthony Edwards",
    "Tyrese Haliburton", "Bam Adebayo", "Donovan Mitchell", "Paolo Banchero",
    "Victor Wembanyama", "Cade Cunningham", "Evan Mobley", "Karl-Anthony Towns",
    "Darius Garland"
]

all_players   = players.get_players()
player_lookup = {p["full_name"]: p for p in all_players}

print("📊 Collecting player career stats...")
player_docs_saved = 0

for name in TOP_PLAYERS:
    player = player_lookup.get(name)
    if not player:
        print(f"  ⚠️  {name} not found")
        continue

    pid    = player["id"]
    career = safe_call(playercareerstats.PlayerCareerStats, player_id=pid)
    info   = safe_call(commonplayerinfo.CommonPlayerInfo, player_id=pid)

    if not career or not info:
        continue

    career_df = career.season_totals_regular_season.get_data_frame()
    info_df   = info.common_player_info.get_data_frame()

    if career_df.empty:
        continue

    lines = [f"PLAYER PROFILE: {name}\n{'='*50}\n"]
    if not info_df.empty:
        row = info_df.iloc[0]
        lines.append(f"Position: {row.get('POSITION','N/A')}")
        lines.append(f"Team: {row.get('TEAM_NAME','N/A')}")
        lines.append(f"Height: {row.get('HEIGHT','N/A')}")
        lines.append(f"Weight: {row.get('WEIGHT','N/A')} lbs")
        lines.append(f"Country: {row.get('COUNTRY','N/A')}")
        lines.append(f"Draft Year: {row.get('DRAFT_YEAR','N/A')}, Round: {row.get('DRAFT_ROUND','N/A')}, Pick: {row.get('DRAFT_NUMBER','N/A')}")
        lines.append(f"Years Pro: {row.get('SEASON_EXP','N/A')}\n")

    lines.append("CAREER STATS BY SEASON:")
    lines.append(f"{'Season':<12} {'Team':<6} {'GP':<5} {'PTS':<7} {'REB':<7} {'AST':<7} {'STL':<6} {'BLK':<6} {'FG%':<7} {'3P%':<7} {'FT%'}")
    lines.append("-" * 80)

    for _, row in career_df.iterrows():
        gp  = row.get("GP", 0)
        pts = round(row.get("PTS", 0) / gp, 1) if gp else 0
        reb = round(row.get("REB", 0) / gp, 1) if gp else 0
        ast = round(row.get("AST", 0) / gp, 1) if gp else 0
        stl = round(row.get("STL", 0) / gp, 1) if gp else 0
        blk = round(row.get("BLK", 0) / gp, 1) if gp else 0
        fg  = round(row.get("FG_PCT", 0) * 100, 1)
        tp  = round(row.get("FG3_PCT", 0) * 100, 1)
        ft  = round(row.get("FT_PCT", 0) * 100, 1)
        lines.append(
            f"{str(row.get('SEASON_ID','')):<12} "
            f"{str(row.get('TEAM_ABBREVIATION','')):<6} "
            f"{gp:<5} {pts:<7} {reb:<7} {ast:<7} {stl:<6} {blk:<6} {fg:<7} {tp:<7} {ft}"
        )

    save_doc(f"player_{name.replace(' ','_')}.txt", "\n".join(lines))
    player_docs_saved += 1
    print(f"  ✅ {name}")

print(f"\n✅ Saved {player_docs_saved} player docs")

# Teams
print("\n🏀 Collecting team records...")
all_teams = teams.get_teams()
team_docs_saved = 0

for team in all_teams:
    result = safe_call(teamyearbyyearstats.TeamYearByYearStats, team_id=team["id"])
    if not result:
        continue
    df = result.team_stats.get_data_frame()
    if df.empty:
        continue

    lines = [f"TEAM PROFILE: {team['full_name']}\n{'='*50}\n"]
    lines.append(f"Abbreviation: {team['abbreviation']}")
    lines.append(f"City: {team['city']}, State: {team['state']}")
    lines.append(f"Year Founded: {team['year_founded']}\n")
    lines.append("SEASON RECORDS (last 10 seasons):")
    lines.append(f"{'Season':<12} {'W':<5} {'L':<5} {'Win%':<8} {'PTS/G':<8} {'OPP PTS/G'}")
    lines.append("-" * 55)

    for _, row in df.tail(10).iterrows():
        lines.append(
            f"{str(row.get('YEAR','')):<12} "
            f"{str(row.get('WINS','')):<5} "
            f"{str(row.get('LOSSES','')):<5} "
            f"{round(row.get('WIN_PCT',0)*100,1):<8} "
            f"{round(row.get('PTS',0),1):<8} "
            f"{round(row.get('OPP_PTS',0),1)}"
        )

    save_doc(f"team_{team['full_name'].replace(' ','_')}.txt", "\n".join(lines))
    team_docs_saved += 1
    print(f"  ✅ {team['full_name']}")

print(f"\n✅ Saved {team_docs_saved} team docs")

# Game logs
print("\n📋 Collecting game logs...")
SEASON = "2024-25"
for name in ["LeBron James", "Stephen Curry", "Giannis Antetokounmpo"]:
    player = player_lookup.get(name)
    if not player:
        continue
    result = safe_call(playergamelog.PlayerGameLog, player_id=player["id"], season=SEASON)
    if not result:
        continue
    df = result.player_game_log.get_data_frame()
    if df.empty:
        continue

    lines = [f"GAME LOG: {name} — {SEASON} Season\n{'='*50}\n"]
    lines.append(f"{'Date':<14} {'Matchup':<20} {'W/L':<5} {'PTS':<6} {'REB':<6} {'AST':<6} {'MIN'}")
    lines.append("-" * 65)
    for _, row in df.head(30).iterrows():
        lines.append(
            f"{str(row.get('GAME_DATE','')):<14} "
            f"{str(row.get('MATCHUP','')):<20} "
            f"{str(row.get('WL','')):<5} "
            f"{str(row.get('PTS','')):<6} "
            f"{str(row.get('REB','')):<6} "
            f"{str(row.get('AST','')):<6} "
            f"{str(row.get('MIN',''))}"
        )
    save_doc(f"gamelog_{name.replace(' ','_')}_{SEASON}.txt", "\n".join(lines))
    print(f"  ✅ {name} game log")

# League leaders
print("\n🏆 Collecting league leaders...")
for stat_cat in ["PTS", "REB", "AST", "STL", "BLK"]:
    result = safe_call(leagueleaders.LeagueLeaders, stat_category_abbreviation=stat_cat, season=SEASON)
    if not result:
        continue
    df = result.league_leaders.get_data_frame().head(20)
    lines = [f"NBA LEAGUE LEADERS — {stat_cat} — {SEASON}\n{'='*50}\n"]
    lines.append(f"{'Rank':<6} {'Player':<25} {'Team':<6} {stat_cat}")
    lines.append("-" * 45)
    for rank, (_, row) in enumerate(df.iterrows(), 1):
        lines.append(f"{rank:<6} {str(row.get('PLAYER','')):<25} {str(row.get('TEAM','')):<6} {row.get(stat_cat,'N/A')}")
    save_doc(f"leaders_{stat_cat}_{SEASON}.txt", "\n".join(lines))
    print(f"  ✅ {stat_cat} leaders")

print(f"\n🏀 Total docs in folder: {len(os.listdir(DOCS_FOLDER))}")

print("🔄 Ingesting all text docs into ChromaDB...")

txt_files = [f for f in os.listdir(DOCS_FOLDER) if f.endswith(".txt")]
print(f"Found {len(txt_files)} files\n")

for txt_file in txt_files:
    print(f"  📄 {txt_file}")
    collection.delete(where={"source": txt_file})  # clear old version first
    ingest_txt(os.path.join(DOCS_FOLDER, txt_file))

print(f"\n🏀 Done! Total chunks in DB: {collection.count()}")

"""Define the chatbot with conversation memory"""

conversation_history = []
MAX_HISTORY = 10

def generate_with_retry(prompt, retries=3, wait=15):
    for attempt in range(retries):
        try:
            response = model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            if "429" in str(e) and attempt < retries - 1:
                print(f"  ⏳ Rate limited — waiting {wait}s...")
                time.sleep(wait)
            else:
                raise e

def rag_chat(user_question: str) -> dict:
    # Retrieve top chunks
    chunks = retrieve(user_question, top_k=8)

    # Build context
    context = "\n---\n".join([
        f"[Source: {c['metadata']['source']}, Page: {c['metadata']['page']}]\n{c['text']}"
        for c in chunks
    ])

    # Build conversation history
    history_str = ""
    if conversation_history:
        history_str = "CONVERSATION HISTORY:\n"
        for exchange in conversation_history[-MAX_HISTORY:]:
            history_str += f"User: {exchange['question']}\n"
            history_str += f"Assistant: {exchange['answer']}\n\n"

    # Build prompt
    prompt = f"""You are an expert NBA chatbot. Answer the user's question using the context below.

IMPORTANT RULES:
- The context contains NBA stats tables. Each row is one season: Season, Team, GP, PTS, REB, AST, STL, BLK, FG%, 3P%, FT%
- PTS = points per game, REB = rebounds per game, AST = assists per game
- Read and interpret these numbers directly
- Always cite your sources as [Source: filename]
- Only say "I don't have that information" if the topic is genuinely absent

{history_str}
CONTEXT:
{context}

USER QUESTION: {user_question}

ANSWER:"""

    answer = generate_with_retry(prompt)

    # Save to memory
    conversation_history.append({"question": user_question, "answer": answer})
    if len(conversation_history) > MAX_HISTORY:
        conversation_history.pop(0)

    return {
        "answer":  answer,
        "sources": list(set([c['metadata']['source'] for c in chunks]))
    }

def chat(question: str):
    print(f"\n{'='*60}")
    print(f"You: {question}")
    print(f"{'='*60}")
    result = rag_chat(question)
    print(f"Bot: {result['answer']}")
    print(f"\n📚 Sources: {', '.join(result['sources'])}")
    print(f"{'='*60}\n")
    time.sleep(3)

print("✅ Chatbot ready")

chat("How many personal fouls before a player gets disqualified?")

chat("What are LeBron James career stats?")

chat("How does he compare to Stephen Curry in assists?")

chat("Who are the current NBA scoring leaders?")

"""Advanced Query"""

def generate_query_variations(question: str) -> list[str]:
    """Uses Gemini to generate 3 variations of the user's question."""
    prompt = f"""Generate 3 different search queries to find information about this question.
Return ONLY the 3 queries, one per line, no numbering, no extra text.

Original question: {question}

3 search queries:"""

    try:
        response = model.generate_content(prompt)
        variations = [q.strip() for q in response.text.strip().split("\n") if q.strip()]
        return [question] + variations[:3]  # original + 3 variations
    except:
        return [question]  # fallback to just original if it fails

def retrieve_multi_query(question: str, top_k=5) -> list:
    """
    Generates query variations, retrieves chunks for each,
    merges results and removes duplicates.
    """
    queries = generate_query_variations(question)
    print(f"  🔍 Searching with {len(queries)} query variations...")

    seen_ids = set()
    all_chunks = []

    for query in queries:
        results = retrieve(query, top_k=top_k)
        for chunk in results:
            # Use text as unique ID to deduplicate
            chunk_id = chunk["metadata"]["doc_id"] + str(chunk["metadata"]["chunk_idx"])
            if chunk_id not in seen_ids:
                seen_ids.add(chunk_id)
                all_chunks.append(chunk)

    # Sort by similarity score so best chunks come first
    all_chunks.sort(key=lambda x: x["score"], reverse=True)

    print(f"  📦 Retrieved {len(all_chunks)} unique chunks after merging")
    return all_chunks[:10]  # return top 10 unique chunks

def rag_chat(user_question: str) -> dict:
    # Use multi-query retrieval instead of single retrieve()
    chunks = retrieve_multi_query(user_question)

    context = "\n---\n".join([
        f"[Source: {c['metadata']['source']}, Page: {c['metadata']['page']}]\n{c['text']}"
        for c in chunks
    ])

    history_str = ""
    if conversation_history:
        history_str = "CONVERSATION HISTORY:\n"
        for exchange in conversation_history[-MAX_HISTORY:]:
            history_str += f"User: {exchange['question']}\n"
            history_str += f"Assistant: {exchange['answer']}\n\n"

    prompt = f"""You are an expert NBA chatbot. Answer the user's question using the context below.

IMPORTANT RULES:
- The context contains NBA stats tables. Each row is one season: Season, Team, GP, PTS, REB, AST, STL, BLK, FG%, 3P%, FT%
- PTS = points per game, REB = rebounds per game, AST = assists per game
- Read and interpret these numbers directly
- Always cite your sources as [Source: filename]
- Only say "I don't have that information" if the topic is genuinely absent

{history_str}
CONTEXT:
{context}

USER QUESTION: {user_question}

ANSWER:"""

    answer = generate_with_retry(prompt)

    conversation_history.append({"question": user_question, "answer": answer})
    if len(conversation_history) > MAX_HISTORY:
        conversation_history.pop(0)

    return {
        "answer":  answer,
        "sources": list(set([c['metadata']['source'] for c in chunks]))
    }

print("✅ Multi-query RAG ready")

chat("How good is LeBron as a playmaker?")